version: '3.8'

services:
  app:
    container_name: beavergate-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file: .env.local
    command: npm run dev
