version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beavergate
    restart: always
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "3000:3000"
